"""empty message

Revision ID: 0ebf4e9c995d
Revises: fc87da620588
Create Date: 2022-07-31 17:59:12.363503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ebf4e9c995d'
down_revision = 'fc87da620588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=128), nullable=False),
    sa.Column('autor', sa.String(length=48), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('contenido', sa.String(length=1024), nullable=True),
    sa.Column('diario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['diario_id'], ['diario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrada')
    # ### end Alembic commands ###
