"""empty message

Revision ID: c03964d42e81
Revises: 0ebf4e9c995d
Create Date: 2022-07-31 18:11:17.984864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c03964d42e81'
down_revision = '0ebf4e9c995d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrada', 'autor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrada', sa.Column('autor', mysql.VARCHAR(length=48), nullable=True))
    # ### end Alembic commands ###
