"""empty message

Revision ID: c605a6aefc22
Revises: fc87da620588
Create Date: 2022-08-01 22:47:02.236069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c605a6aefc22'
down_revision = 'fc87da620588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=120), nullable=True),
    sa.Column('texto', sa.String(length=1024), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('id_diario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_diario'], ['diario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entrada')
    # ### end Alembic commands ###
